language: C
group:    stable
dist:     trusty
os:       linux

compiler:
  - clang
  - gcc

before_script:
  - autoconf --version
  - sudo apt-get -qq update
  - sudo apt-get install -y automake autoconf
  - bash autogen.sh
